<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="MediatR" Version="14.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CqrsApp.Application\CqrsApp.Application.csproj" />
      <ProjectReference Include="..\CqrsApp.Infrastructure\CqrsApp.Infrastructure.csproj" />
      <ProjectReference Include="..\CqrsApp.Persistence\CqrsApp.Persistence.csproj" />
      <ProjectReference Include="..\CqrsApp.Presentation\CqrsApp.Presentation.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

</Project>
