<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CqrsApp.Application\CqrsApp.Application.csproj" />
      <ProjectReference Include="..\CqrsApp.Infrastructure\CqrsApp.Infrastructure.csproj" />
    </ItemGroup>

</Project>
